/* eslint-disable max-lines */
const one = [
  {
    name: 'Avaí/Kindermann',
    totalPoints: 4,
    totalGames: 6,
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 4,
    goalsFavor: 4,
    goalsOwn: 9,
    goalsBalance: -5,
    efficiency: 22.22,
  },
  {
    name: 'Bahia',
    totalPoints: 2,
    totalGames: 6,
    totalVictories: 0,
    totalDraws: 2,
    totalLosses: 4,
    goalsFavor: 4,
    goalsOwn: 9,
    goalsBalance: -5,
    efficiency: 11.11,
  },
  {
    name: 'Botafogo',
    totalPoints: 4,
    totalGames: 5,
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 3,
    goalsFavor: 3,
    goalsOwn: 8,
    goalsBalance: -5,
    efficiency: 26.67,
  },
  {
    name: 'Corinthians',
    totalPoints: 12,
    totalGames: 5,
    totalVictories: 4,
    totalDraws: 0,
    totalLosses: 1,
    goalsFavor: 12,
    goalsOwn: 3,
    goalsBalance: 9,
    efficiency: 80,
  },
  {
    name: 'Cruzeiro',
    totalPoints: 4,
    totalGames: 5,
    totalVictories: 1,
    totalDraws: 1,
    totalLosses: 3,
    goalsFavor: 8,
    goalsOwn: 10,
    goalsBalance: -2,
    efficiency: 26.67,
  },
  {
    name: 'Ferroviária',
    totalPoints: 10,
    totalGames: 6,
    totalVictories: 3,
    totalDraws: 1,
    totalLosses: 2,
    goalsFavor: 8,
    goalsOwn: 7,
    goalsBalance: 1,
    efficiency: 55.56,
  },
  {
    name: 'Flamengo',
    totalPoints: 5,
    totalGames: 5,
    totalVictories: 1,
    totalDraws: 2,
    totalLosses: 2,
    goalsFavor: 2,
    goalsOwn: 5,
    goalsBalance: -3,
    efficiency: 33.33,
  },
  {
    name: 'Grêmio',
    totalPoints: 10,
    totalGames: 5,
    totalVictories: 3,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 9,
    goalsOwn: 8,
    goalsBalance: 1,
    efficiency: 66.67,
  },
  {
    name: 'Internacional',
    totalPoints: 10,
    totalGames: 6,
    totalVictories: 3,
    totalDraws: 1,
    totalLosses: 2,
    goalsFavor: 8,
    goalsOwn: 8,
    goalsBalance: 0,
    efficiency: 55.56,
  },
  {
    name: 'Minas Brasília',
    totalPoints: 2,
    totalGames: 5,
    totalVictories: 0,
    totalDraws: 2,
    totalLosses: 3,
    goalsFavor: 4,
    goalsOwn: 9,
    goalsBalance: -5,
    efficiency: 13.33,
  },
  {
    name: 'Napoli-SC',
    totalPoints: 2,
    totalGames: 5,
    totalVictories: 0,
    totalDraws: 2,
    totalLosses: 3,
    goalsFavor: 3,
    goalsOwn: 12,
    goalsBalance: -9,
    efficiency: 13.33,
  },
  {
    name: 'Palmeiras',
    totalPoints: 13,
    totalGames: 5,
    totalVictories: 4,
    totalDraws: 1,
    totalLosses: 0,
    goalsFavor: 17,
    goalsOwn: 5,
    goalsBalance: 12,
    efficiency: 86.67,
  },
  {
    name: 'Real Brasília',
    totalPoints: 13,
    totalGames: 6,
    totalVictories: 4,
    totalDraws: 1,
    totalLosses: 1,
    goalsFavor: 8,
    goalsOwn: 6,
    goalsBalance: 2,
    efficiency: 72.22,
  },
  {
    name: 'Santos',
    totalPoints: 11,
    totalGames: 5,
    totalVictories: 3,
    totalDraws: 2,
    totalLosses: 0,
    goalsFavor: 12,
    goalsOwn: 6,
    goalsBalance: 6,
    efficiency: 73.33,
  },
  {
    name: 'São José-SP',
    totalPoints: 6,
    totalGames: 5,
    totalVictories: 2,
    totalDraws: 0,
    totalLosses: 3,
    goalsFavor: 5,
    goalsOwn: 6,
    goalsBalance: -1,
    efficiency: 40,
  },
  {
    name: 'São Paulo',
    totalPoints: 11,
    totalGames: 6,
    totalVictories: 3,
    totalDraws: 2,
    totalLosses: 1,
    goalsFavor: 11,
    goalsOwn: 7,
    goalsBalance: 4,
    efficiency: 61.11,
  },
];

const two = [
  {
    name: 'Avaí/Kindermann',
    totalVictories: 1,
    totalDraws: 1,
    totalPoints: 4,
    totalGames: 6,
    totalLosses: 4,
    goalsFavor: 4,
    goalsOwn: 9,
    goalsBalance: -5,
    efficiency: NaN,
  },
  {
    name: 'Bahia',
    totalVictories: 0,
    totalDraws: 2,
    totalPoints: 2,
    totalGames: 6,
    totalLosses: 4,
    goalsFavor: 4,
    goalsOwn: 9,
    goalsBalance: -5,
    efficiency: NaN,
  },
  {
    name: 'Botafogo',
    totalVictories: 1,
    totalDraws: 1,
    totalPoints: 4,
    totalGames: 5,
    totalLosses: 3,
    goalsFavor: 3,
    goalsOwn: 8,
    goalsBalance: -5,
    efficiency: NaN,
  },
  {
    name: 'Corinthians',
    totalVictories: 4,
    totalDraws: 0,
    totalPoints: 12,
    totalGames: 5,
    totalLosses: 1,
    goalsFavor: 12,
    goalsOwn: 3,
    goalsBalance: 9,
    efficiency: NaN,
  },
  {
    name: 'Cruzeiro',
    totalVictories: 1,
    totalDraws: 1,
    totalPoints: 4,
    totalGames: 5,
    totalLosses: 3,
    goalsFavor: 8,
    goalsOwn: 10,
    goalsBalance: -2,
    efficiency: NaN,
  },
  {
    name: 'Ferroviária',
    totalVictories: 3,
    totalDraws: 1,
    totalPoints: 10,
    totalGames: 6,
    totalLosses: 2,
    goalsFavor: 8,
    goalsOwn: 7,
    goalsBalance: 1,
    efficiency: NaN,
  },
  {
    name: 'Flamengo',
    totalVictories: 1,
    totalDraws: 2,
    totalPoints: 5,
    totalGames: 5,
    totalLosses: 2,
    goalsFavor: 2,
    goalsOwn: 5,
    goalsBalance: -3,
    efficiency: NaN,
  },
  {
    name: 'Grêmio',
    totalVictories: 3,
    totalDraws: 1,
    totalPoints: 10,
    totalGames: 5,
    totalLosses: 1,
    goalsFavor: 9,
    goalsOwn: 8,
    goalsBalance: 1,
    efficiency: NaN,
  },
  {
    name: 'Internacional',
    totalVictories: 3,
    totalDraws: 1,
    totalPoints: 10,
    totalGames: 6,
    totalLosses: 2,
    goalsFavor: 8,
    goalsOwn: 8,
    goalsBalance: 0,
    efficiency: NaN,
  },
  {
    name: 'Minas Brasília',
    totalVictories: 0,
    totalDraws: 2,
    totalPoints: 2,
    totalGames: 5,
    totalLosses: 3,
    goalsFavor: 4,
    goalsOwn: 9,
    goalsBalance: -5,
    efficiency: NaN,
  },
  {
    name: 'Napoli-SC',
    totalVictories: 0,
    totalDraws: 2,
    totalPoints: 2,
    totalGames: 5,
    totalLosses: 3,
    goalsFavor: 3,
    goalsOwn: 12,
    goalsBalance: -9,
    efficiency: NaN,
  },
  {
    name: 'Palmeiras',
    totalVictories: 4,
    totalDraws: 1,
    totalPoints: 13,
    totalGames: 5,
    totalLosses: 0,
    goalsFavor: 17,
    goalsOwn: 5,
    goalsBalance: 12,
    efficiency: NaN,
  },
  {
    name: 'Real Brasília',
    totalVictories: 4,
    totalDraws: 1,
    totalPoints: 13,
    totalGames: 6,
    totalLosses: 1,
    goalsFavor: 8,
    goalsOwn: 6,
    goalsBalance: 2,
    efficiency: NaN,
  },
  {
    name: 'Santos',
    totalVictories: 3,
    totalDraws: 2,
    totalPoints: 11,
    totalGames: 5,
    totalLosses: 0,
    goalsFavor: 12,
    goalsOwn: 6,
    goalsBalance: 6,
    efficiency: NaN,
  },
  {
    name: 'São José-SP',
    totalVictories: 2,
    totalDraws: 0,
    totalPoints: 6,
    totalGames: 5,
    totalLosses: 3,
    goalsFavor: 5,
    goalsOwn: 6,
    goalsBalance: -1,
    efficiency: NaN,
  },
  {
    name: 'São Paulo',
    totalVictories: 3,
    totalDraws: 2,
    totalPoints: 11,
    totalGames: 6,
    totalLosses: 1,
    goalsFavor: 11,
    goalsOwn: 7,
    goalsBalance: 4,
    efficiency: NaN,
  },
];

console.log(one[0]);
console.log(two[0]);
